name = "cha-panela-api"
main = "worker.js"
compatibility_date = "2026-03-14"

[[d1_databases]]
binding = "DB"
database_name = "cha-panela-db"
database_id = "SEU_DATABASE_ID"

[vars]
GOOGLE_CLIENT_ID = "SEU_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
